### ISSUE TITLE
set severity of RHEL-07-010491 to high

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/community#1]
DISA requests setting severity of RHEL-07-010491 to high... we don't have a rule mapped to that control.

Perhaps they mean grub2_uefi_password, mapped to 010490 ?

**Comment by tedbrunell** [comment]
Just rebuilt RHEL 7 content. "Set the UEFI Boot Loader Password" is still mapped to RHEL-07-010490 which is planned to be removed by DISA in the next release of the DoD STIG.  RHEL-07-010490 was for RHEL versions 7.2 and earlier.  RHEL-07-010491 is the STIG ID for RHEL 7.3+ the "Set the UEFI Boot Loader Password" rule should be changed to reflect that.
