### ISSUE TITLE
[DISA] Create rule for deny=3 (breakout from RHEL-07-010320)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/community#10]
Existing content does not have dedicated check for deny=3, but it's implied in RHEL-07-010320. DISA needs to create new rule that aligns to DoD and Red Hat recommendations (copy/paste from vendor guidance)

**Comment by tedbrunell** [comment]
This rule is in Red Hat content as 4 rules.  Waiting on next RHEL 7 DoD STIG release by DISA includes the same 4 rules.
