### ISSUE TITLE
DISA: wrong ciphers in sshd_use_approved_macs

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/community#12]
DISA:
> current ciphers are wrong:
 <ind:pattern operation="pattern match">^[\s]*(?i)MACs(?-i)[\s]+((hmac-sha1|hmac-sha2-256|hmac-sha2-512|hmac-sha1-etm@openssh\.com|hmac-sha2-256-etm@openssh\.com|hmac-sha2-512-etm@openssh\.com),?)+[\s]*(?:|(?:#.*))?$</ind:pattern>

**Comment by ajd394** [comment]
It seems that SHA1 is approved for HMAC
[NIST 800-131a](https://csrc.nist.gov/publications/detail/sp/800-131a/rev-1/final)

However from the current STIG benchmark appears to only permit the following
```
for all value, at least one of the following must be true:
value must be equal to 'hmac-sha2-512'
value must be equal to 'hmac-sha2-256'
```
