### ISSUE TITLE
stig-rhel6-disa includes TMOUT

### ISSUE THREAD

**Issue by jamescassell** [ComplianceAsCode/community#16]
#### Description of problem:
There is no mention of TMOUT in the RHEL 6 STIG V1R18

#### SCAP Security Guide Version:
0.1.38

#### Operating System Version:
RHEL 6.9

#### Steps to Reproduce:

1. Run oscap with profile stig-rhel6-disa
2. see failure for content_rule_accounts_tmout

#### Actual Results:
failed

#### Expected Results:
rule not present

#### Addition Information/Debugging Steps:
The only mentions of a session timeout is wrt sshd `ClientAliveInterval` and `ClientAliveCountMax`

**Comment by tedbrunell** [comment]
@shawndwells account_tmout does not appear the the RHEL 6 STIG table or the CCI table for RHEL 6.  It does appear in the RHEL 6 STIG TestInfo table but has no check or fix content associated with it.  Do we need the test?  There are setting in published DoD content and SSG content for GNOME inactivity as well as SSH activity timeouts.

**Comment by jamescassell** [comment]
What was the resolution?

**Comment by redhatrises** [comment]
Unfortunately, this isn't going away, and we won't be able to influence changing this requirement.

**Comment by redhatrises** [comment]
We are also re-reviewing all of the rhel7 disa content from DISA itself... since we haven't done an update in an acceptable time frame.
