### ISSUE TITLE
set severity of accounts_password_pam_retry to medium

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/community#2]
DISA requests severity of accounts_password_pam_retry to be medium.

@tedbrunell can they share justification for medium over low?

**Comment by tedbrunell** [comment]
Rebuilt RHEL 7 content.  This looks resolved and can be closed.  Thanks.

**Comment by redhatrises** [comment]
Thanks @tedbrunell. Closing. Let me know if you cannot close tickets.
