### ISSUE TITLE
[DISA] RHEL-07-040680: postfix mail relaying

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/community#9]
- DISA included rule with objection from vendor and DoD. 
- Out of scope of base operating system. 
- Other vendors not held to same standard (Windows, VMWare...)

**Comment by tedbrunell** [comment]
Suggest that this issue be closed.  The rule in included in the content as postfix_prevent_unrestricted_relay.  Postfix is included in the RHEL install.
